[package]
name = "quote_crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = { version = "1" }
syn = { version = "2", features = ["full"] }
proc-macro2 = { version = "1" }